version: '3'

services:

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - custom-network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    expose:
      - 9092
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - custom-network

  client:
    container_name: client
    build:
      context: ../client
      dockerfile: Dockerfile
    depends_on:
      - kafka
    restart: on-failure
    ports:
      - 8082:8082
    networks:
      - custom-network

  subscriber:
    container_name: subscriber
    build:
      context: ../subscriber
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - client
    restart: on-failure
    ports:
      - 8081:8081
    networks:
      - custom-network

  producer:
    container_name: producer
    build:
      context: ../producer
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - client
      - subscriber
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge